version: "3.9" 

services: 
    main-service:
        container_name: python-3.8.7
        image: python-3.8.7
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
